# Generated by Django 3.2.3 on 2021-06-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_rename_username_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='joindate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='가입일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='money',
            field=models.IntegerField(blank=True, default=1000, verbose_name='가상머니'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=20, verbose_name='별명'),
        ),
    ]
